# Playbook zur Konfiguration aller Servern von services

- hosts: services
  remote_user: root
  roles:
    - backports-kernel
    - interfaces_services
    - alfred_json
    - ffmap_backend
    - nginx
    - meshviewer
    - bind

