# Playbook zur Konfiguration aller Servern von services

- hosts: services
  remote_user: root
  roles:
    - { role: backports-kernel, tags: "backports-kernel"}
    - { role: services_interfaces, tags: "services_interfaces"}
    - { role: alfred_json, tags: "alfred_json"}
    - { role: services_ffmap_backend, tags: "services_ffmap_backend"}
    - { role: services_ngix, tags: "services_ngix"}
    - { role: services_meshviewer, tags: "services_meshviewer"}
    - { role: services_node-stats, tags: "services_node-stats"}
    - { role: services_bind, tags: "services_bind"}
    - { role: services_ffapi, tags: "services_ffapi"}

