# Playbook zur Konfiguration aller Servern von services

- hosts: services
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: motd, tags: "motd"}
    - { role: backports-kernel, tags: "backports-kernel"}
#    - { role: tunearpcache, tags: "tunearpcache"}
#    - { role: services_interfaces, tags: "services_interfaces"}
#    - { role: alfred_json, tags: "alfred_json"}
    - { role: services_nginx, tags: "services_nginx"}
#    - { role: services_node-stats, tags: "services_node-stats"}
    - { role: services_bind, tags: "services_bind"}
    - { role: services_ffapi, tags: "services_ffapi"}
    - { role: services_graphite, tags: "services_graphite"}
    - { role: collectd, tags: "collectd"}
#    - { role: py_respondd, tags: "py_respondd"}

